<?php

return [
    'categories' => [
        [
            'key' => 'internet',
            'label' => 'Internet & Technology',
            'items' => [
                'Wi-Fi',
                'High-Speed Internet',
                'Power Backup',
                'Computer',
                'Photocopy Machine',
                'Laptop Charging Points',
                'Mobile Charging Points',
                'Printer',
                'Scanner',
                'CCTV',
            ],
        ],
        [
            'key' => 'seating',
            'label' => 'Seating & Study Facilities',
            'items' => [
                'Individual Study Cabins',
                'Shared Tables',
                'Reading Room',
                'Silent Zone',
                'Discussion Rooms',
                'Cubicles',
                'Ergonomic Chairs',
                'Desk Lamps',
                'Whiteboard',
                'Lockers',
                'Book Shelves',
                'Newspaper Section',
            ],
        ],
        [
            'key' => 'comfort',
            'label' => 'Air Conditioning & Comfort',
            'items' => [
                'Full AC',
                'Partial AC',
                'Ceiling Fans',
                'Room Heaters',
                'Air Purifier',
                'Natural Light',
                'Comfortable Seating',
            ],
        ],
        [
            'key' => 'water',
            'label' => 'Water & Refreshments',
            'items' => [
                'RO Drinking Water',
                'Water Cooler',
                'Tea/Coffee',
                'Vending Machine',
                'Pantry',
                'Cafeteria Nearby',
                'Hot Water',
                'Filtered Water',
            ],
        ],
        [
            'key' => 'safety',
            'label' => 'Safety & Security',
            'items' => [
                'CCTV Surveillance',
                'Security Guard',
                'Fire Extinguisher',
                'First Aid Kit',
                'Biometric Entry',
                'Emergency Exit',
                '24x7 Security',
            ],
        ],
        [
            'key' => 'hygiene',
            'label' => 'Washroom & Hygiene',
            'items' => [
                'Clean Washrooms',
                'Separate Washrooms',
                'Hand Sanitizer',
                'Regular Cleaning',
                'Tissue Paper',
                'Soap Dispenser',
                'Hygiene Kits',
            ],
        ],
        [
            'key' => 'parking',
            'label' => 'Parking & Accessibility',
            'items' => [
                'Two-Wheeler Parking',
                'Four-Wheeler Parking',
                'Free Parking',
                'Wheelchair Access',
                'Elevator',
                'Ramp Access',
                'Nearby Public Transport',
            ],
        ],
        [
            'key' => 'additional',
            'label' => 'Additional Facilities',
            'items' => [
                '24x7 Open',
                'Night Shift',
                'Female-Only Section',
                'Male-Only Section',
                'Prayer Room',
                'Exam Prep Corner',
                'Mentorship Desk',
                'Music-Free Zone',
                'Generator Backup',
                'Library Books',
            ],
        ],
    ],
];
